### POST Request to Create an Income
POST http://localhost:8080/incomes/createIncome
Content-Type: application/json

{
  "source": "Bank",
  "amount": 500.0
}

### GET Request to Get all Incomes
GET http://localhost:8080/incomes

### GET Request to Get Income with id = 2
GET http://localhost:8080/incomes/2

### PUT Request to Update Income with id = 3
PUT http://localhost:8080/incomes/3
Content-Type: application/json

{
  "source": "Payment of interest on the deposit",
  "amount": 555.05
}

### DELETE Request to Delete Income with id = 2
DELETE http://localhost:8080/incomes/2
